apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointmentservice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointmentservice
  template:
    metadata:
      labels:
        app: appointmentservice
    spec:
      containers:
        - name: appointmentservice
          image: 333813598365.dkr.ecr.eu-central-1.amazonaws.com/appointmentservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000   # üî• change if your app uses different port
---
apiVersion: v1
kind: Service
metadata:
  name: appointmentservice
  namespace: default
spec:
  type: LoadBalancer   # ‚≠ê exposes externally via AWS ELB
  selector:
    app: appointmentservice
  ports:
    - port: 80
      targetPort: 3000   # must match containerPort
      protocol: TCP