name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Build and Push Docker"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write     # ‚≠ê REQUIRED for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::333813598365:role/GithubRole

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name akhil-eks --region eu-central-1

      - name: Deploy
        run: kubectl apply -f k8s/